# Generated by Django 4.2.8 on 2025-05-06 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('test_recommendation', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine_recommendation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_model.diagnosis')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_model.symptom')),
            ],
            options={
                'unique_together': {('diagnosis', 'symptom')},
            },
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='primary_disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_diagnoses', to='ai_model.disease'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptoms',
            field=models.ManyToManyField(through='ai_model.DiagnosisSymptom', to='ai_model.symptom'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
